version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo 'Installing...'
  build:
    commands:
      - echo 'Building...'
  post_build:
    commands:
      - aws s3 sync --exact-timestamps --delete build s3://cb-dev-static